@startuml PlayerLogic
state "PlayerLogic State" as RescueDrone_PlayerLogic_State {
  state "Alive" as RescueDrone_PlayerLogic_State_Alive {
    state "Idle" as RescueDrone_PlayerLogic_State_Idle
    state "Moving" as RescueDrone_PlayerLogic_State_Moving
  }
  state "Dead" as RescueDrone_PlayerLogic_State_Dead
  state "Disabled" as RescueDrone_PlayerLogic_State_Disabled
}

RescueDrone_PlayerLogic_State_Alive --> RescueDrone_PlayerLogic_State_Alive : OnInputEvent
RescueDrone_PlayerLogic_State_Alive --> RescueDrone_PlayerLogic_State_Alive : OnPhysicsTick
RescueDrone_PlayerLogic_State_Disabled --> RescueDrone_PlayerLogic_State_Idle : Enable
RescueDrone_PlayerLogic_State_Idle --> RescueDrone_PlayerLogic_State_Idle : AfterMove
RescueDrone_PlayerLogic_State_Idle --> RescueDrone_PlayerLogic_State_Moving : StartedMoving
RescueDrone_PlayerLogic_State_Moving --> RescueDrone_PlayerLogic_State_Idle : StoppedMoving
RescueDrone_PlayerLogic_State_Moving --> RescueDrone_PlayerLogic_State_Moving : AfterMove

RescueDrone_PlayerLogic_State_Alive : OnOnInputEvent → ToggleMouseCapture
RescueDrone_PlayerLogic_State_Alive : OnOnPhysicsTick → RotationComputed, VelocityComputed
RescueDrone_PlayerLogic_State_Disabled : OnLevelStart() → ToggleMouseCapture
RescueDrone_PlayerLogic_State_Idle : OnEnter → ToggleBobEffect
RescueDrone_PlayerLogic_State_Idle : OnExit → ToggleBobEffect

[*] --> RescueDrone_PlayerLogic_State_Disabled
@enduml