@startuml PlayerCameraLogic
state "PlayerCameraLogic State" as RescueDrone_PlayerCameraLogic_State {
  state "Disabled" as RescueDrone_PlayerCameraLogic_State_Disabled
  state "Enabled" as RescueDrone_PlayerCameraLogic_State_Enabled
}

RescueDrone_PlayerCameraLogic_State_Disabled --> RescueDrone_PlayerCameraLogic_State_Enabled : Enable
RescueDrone_PlayerCameraLogic_State_Enabled --> RescueDrone_PlayerCameraLogic_State_Disabled : Disable
RescueDrone_PlayerCameraLogic_State_Enabled --> RescueDrone_PlayerCameraLogic_State_Enabled : OnPhysicsProcessTick

RescueDrone_PlayerCameraLogic_State_Enabled : HandleCameraRotationInput() → RotationComputed
RescueDrone_PlayerCameraLogic_State_Enabled : HandleCameraZoomInput() → ZoomComputed

[*] --> RescueDrone_PlayerCameraLogic_State_Disabled
@enduml